### ISSUE TITLE
Fixed Server host and port

### ISSUE THREAD

**Issue by msblim** [lopezpaolot/itrsExam#1]
How can we modify this so that I can run the server on another machine using a configurable port?

https://github.com/lopezpaolot/itrsExam/blob/15591c53b7ac786f6b451c1962e5150d1754b340/itrsClient/itrsClient/itrsClient.cpp#L16

**Comment by lopezpaolot** [comment]
Fixed on branch "issue_1_3_fixes" merged to main https://github.com/lopezpaolot/itrsExam/commit/3f4c0c38407a7967d8314187dd53bbf0a328f8f7
