### ISSUE TITLE
Server does not log message

### ISSUE THREAD

**Issue by msblim** [lopezpaolot/itrsExam#2]
In the exam specifications, it was mentioned that the server should log the messages:

> Server, which receives messages from the network, logs them, and echoes them back to the client

The current version does not log the messages yet.
Where should this be logged in the code?

**Comment by lopezpaolot** [comment]
Fixed on branch "issue_1_3_fixes" merged to main https://github.com/lopezpaolot/itrsExam/commit/3f4c0c38407a7967d8314187dd53bbf0a328f8f7
