### ISSUE TITLE
Proper clean-up

### ISSUE THREAD

**Issue by msblim** [lopezpaolot/itrsExam#3]
Currently, this is in a while loop, and thus no proper exit/cleanup can be performed.
We can add a handling like if the user types 'exit', the client application will exit.

https://github.com/lopezpaolot/itrsExam/blob/15591c53b7ac786f6b451c1962e5150d1754b340/itrsClient/itrsClient/itrsClient.cpp#L27

**Comment by lopezpaolot** [comment]
Fixed on branch "issue_1_3_fixes" merged to main https://github.com/lopezpaolot/itrsExam/commit/3f4c0c38407a7967d8314187dd53bbf0a328f8f7
