### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by rnaval** [lopezpaolot/itrsExam#6]
https://github.com/lopezpaolot/itrsExam/blob/15591c53b7ac786f6b451c1962e5150d1754b340/itrsServer/itrsServer/itrsServer.cpp#L119

Is this function thread-safe? If not, how can we make sure that it can handle multiple threads?

**Comment by lopezpaolot** [comment]
std::cout is technically thread safe but output might be mixed up because of the << operator.
Added a mutex lock for this method. Fixed on branch issues5_6_fixes, merged to main in commit https://github.com/lopezpaolot/itrsExam/commit/6c386521f25518ffc902c9106aa60c47c4974f8f.
